---
title: Curriculum vitae
---

[Download full CV in PDF.](static/cv/cv-chavan.pdf) 

## CV summary

### Education

- Ph.D. Ecology and Evolutionary Biology • Yale University (adviser: Dr. Gunter Wagner) • 2012–2018
- M.Sc. Biology • Tata Institute of Fundamental Research (adviser: Dr. Himanshu Sinha) • 2009–2012
- B.Sc. Biotechnology • Fergusson College, University of Pune • 2006–2009

### Appointments

- Postdoctoral Associate •	2021–Present
- CRI Irvington Postdoctoral Fellow	• 2019–2021 &
  - Department of Immunobiology
  - Yale University, School of Medicine
  - Adviser: Dr. Ruslan Medzhitov
  
### Funding, Fellowships, and Prizes
#### Fellowships and Prizes

- John Spangler Nicholas Prize (for doctoral dissertation, Yale University)	• 2019
- CRI Irvington Postdoctoral Fellowship (Cancer Research Institute, New York)	• 2019–2021 
- Finalist, Best Student Presentation Award (Society for Integrative and Comparative Biology; DEDB)	• 2018
- Student Poster Prize (Complex Traits Symposium, Society for Molecular Biology and Evolution) • 2017

#### Research and Travel Grants

- Young Investigator Travel Award (Society for Molecular Biology and Evolution)	• 2017
- Chair’s Fund, Ecology & Evolutionary Biology (Yale University) • 2016
- Conference Travel Fellowship (Yale University) • 2016 
- Chair’s Fund, Ecology & Evolutionary Biology (Yale University) • 2014

#### Graduate School Funding Sources

- Charles A. & June R. P. Ross Fellowship (Yale University)	• 2016–2017
- Leo F. Rettger Fellowship (Yale University)	• 2014–2015
- Robert W. Carle Scholarship (Yale University)	• 2013–2014
- Junior Research Scholarship (Tata Institute of Fundamental Research, Department of Atomic Energy, Government of India) • 2009–2012

### Media Coverage

- Coverage for talk at SICB, San Francisco 2018 (now published as Chavan et al, *MBE* 2020)
  - Tamed immune reaction aids pregnancy  
  Elizabeth Pennisi, [*Science* 359(6373):260](https://doi.org/10.1126/science.359.6373.260) • 
  pdf: [download](static/cv/pennisi_2018_science.pdf)
  - Armadillo and rabbit genes reveal how pregnancy evolved  
  Amy Maxmen, [*Nature*](https://www.nature.com/articles/d41586-018-00341-w) (Republished by [*Scientific American*](https://www.scientificamerican.com/article/armadillo-hedgehog-and-rabbit-genes-reveal-how-pregnancy-evolved/))
  - When bad things become good: was inflammation modified to become implantation in placental mammals?  
  Ashley Booth, [*SICB Press Release*](https://www.newswise.com/articles/when-a-bad-thing-becomes-good%3A-was-inflammation-modified-to-become-implantation-in-placental-mammals%3F)
- Coverage for Griffith et. al, *PNAS* 2017
  - Evolution of pregnancy may be key to better reproductive technologies today  
  Jon Atherton, [*Yale News*](https://news.yale.edu/2017/07/24/evolution-pregnancy-may-be-key-better-reproductive-technologies-today)


